// Package bdd runs ./features with godog (generated by gherkin-ai).
// Steps are pending until implemented; non-strict mode reports them without failing.
package bdd

import (
	"context"
	"testing"

	"github.com/cucumber/godog"

	"transactional-system-go-chi/internal/domain"
)

type world struct {
	aggregate *domain.OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate
}

func (w *world) GivenUnComandoCreateOrderCommandEnviadoAApiV1OrdersConIdempotencyKe(ctx context.Context) error {
	// Pending: drive w.aggregate (or the HTTP API) and assert the outcome.
	return godog.ErrPending
}

func (w *world) WhenLaRutaChiProcesaLaPeticionDentroDeUnContextWithTimeoutDe5Segu(ctx context.Context) error {
	// Pending: drive w.aggregate (or the HTTP API) and assert the outcome.
	return godog.ErrPending
}

func (w *world) ThenDebeAbrirUnaTransaccionPgxTxYRegistrarElAgregadoYElRegistroOut(ctx context.Context) error {
	// Pending: drive w.aggregate (or the HTTP API) and assert the outcome.
	return godog.ErrPending
}

func (w *world) ThenDebeDevolverHttp201CreatedConElPayloadJsonIdeomaticoEnGo(ctx context.Context) error {
	// Pending: drive w.aggregate (or the HTTP API) and assert the outcome.
	return godog.ErrPending
}

func (w *world) ThenLaSuiteGoTestRaceDebeVerificarLaAusenciaDeCondicionesDeCarrera(ctx context.Context) error {
	// Pending: drive w.aggregate (or the HTTP API) and assert the outcome.
	return godog.ErrPending
}

func initializeScenario(sc *godog.ScenarioContext) {
	w := &world{}
	sc.Before(func(ctx context.Context, _ *godog.Scenario) (context.Context, error) {
		aggregate, err := domain.NewOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate("scenario-aggregate")
		w.aggregate = aggregate
		return ctx, err
	})
	sc.Step(`^un comando \x60CreateOrderCommand\x60 enviado a \x60\/api\/v1\/orders\x60 con \x60idempotency_key\x60 "IDEM-GO-122"$`, w.GivenUnComandoCreateOrderCommandEnviadoAApiV1OrdersConIdempotencyKe)
	sc.Step(`^la ruta \x60chi\x60 procesa la petición dentro de un \x60context\.WithTimeout\x60 de 5 segundos$`, w.WhenLaRutaChiProcesaLaPeticionDentroDeUnContextWithTimeoutDe5Segu)
	sc.Step(`^debe abrir una transacción \x60pgx\.Tx\x60 y registrar el agregado y el registro Outbox$`, w.ThenDebeAbrirUnaTransaccionPgxTxYRegistrarElAgregadoYElRegistroOut)
	sc.Step(`^debe devolver HTTP 201 Created con el payload JSON ideomático en Go$`, w.ThenDebeDevolverHttp201CreatedConElPayloadJsonIdeomaticoEnGo)
	sc.Step(`^la suite \x60go test -race \.\/\.\.\.\x60 debe verificar la ausencia de condiciones de carrera \(data races\)$`, w.ThenLaSuiteGoTestRaceDebeVerificarLaAusenciaDeCondicionesDeCarrera)
}

func TestFeatures(t *testing.T) {
	suite := godog.TestSuite{
		ScenarioInitializer: initializeScenario,
		Options: &godog.Options{
			Format:   "pretty",
			Paths:    []string{"../../features"},
			Strict:   false,
			TestingT: t,
		},
	}
	if suite.Run() != 0 {
		t.Fatal("feature run failed")
	}
}
