// Package domain holds the domain kernel for "Orquestación de Saga Idempotente con Goroutines en Go 1.22 y chi" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
package domain

import (
	"errors"
	"fmt"
	"strings"
	"time"
)

// ErrValidation is wrapped by every domain validation failure.
var ErrValidation = errors.New("domain validation error")

type State string

const (
	StatePending State = "PENDING"
)

type EventType string

const (
	EventProcessOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiCompleted EventType = "ProcessOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiCompleted"
	EventOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiProcessed EventType = "OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiProcessed"
)

type Command struct {
	ID      string
	Payload map[string]any
}

type DomainEvent struct {
	Type        EventType
	AggregateID string
	Version     int64
	OccurredOn  time.Time
	Payload     map[string]any
}

type OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate struct {
	ID            string
	State         State
	Version       int64
	pendingEvents []DomainEvent
}

func NewOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate(id string) (*OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate, error) {
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("%w: OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChi id is required", ErrValidation)
	}
	return &OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate{ID: id, State: StatePending}, nil
}

// PendingEvents returns the events recorded since the aggregate was loaded (to be saved via the outbox).
func (a *OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate) PendingEvents() []DomainEvent {
	return append([]DomainEvent(nil), a.pendingEvents...)
}

func (a *OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate) ProcessOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChi(cmd Command) (DomainEvent, error) {
	if err := a.assertValid(cmd); err != nil {
		return DomainEvent{}, err
	}
	return a.record(EventProcessOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiCompleted, cmd.Payload), nil
}

func (a *OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate) assertValid(cmd Command) error {
	if strings.TrimSpace(cmd.ID) == "" {
		return fmt.Errorf("%w: command id is required", ErrValidation)
	}
	if cmd.ID != a.ID {
		return fmt.Errorf("%w: command targets %s, not %s", ErrValidation, cmd.ID, a.ID)
	}
	return nil
}

func (a *OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiAggregate) record(t EventType, payload map[string]any) DomainEvent {
	a.Version++
	if payload == nil {
		payload = map[string]any{}
	}
	event := DomainEvent{Type: t, AggregateID: a.ID, Version: a.Version, OccurredOn: time.Now().UTC(), Payload: payload}
	a.pendingEvents = append(a.pendingEvents, event)
	return event
}
