/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Orquestación de Saga Idempotente con Goroutines en Go 1.22 y chi
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiFixture {
  id: string;

}

export function createOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiFixture(): OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "un comando `CreateOrderCommand` enviado a `/api/v1/orders` con `idempotency_key` \"IDEM-GO-122\""
];
