/* ==========================================================================
   Generated Domain Contracts & Go Structs
   Feature: Orquestación de Saga Idempotente con Goroutines en Go 1.22 y chi
   Stack: Go + chi + go-orm
   Generated by gherkin-ai CLI v3.0.0
   ========================================================================== */

package contracts

import (
	"context"
	"time"
)

// --------------------------------------------------------------------------
// 1. Domain Event Interface
// --------------------------------------------------------------------------
type IDomainEvent interface {
	GetEventID() string
	GetOccurredOn() time.Time
	GetEventType() string
}



// --------------------------------------------------------------------------
// 2. Command DTO Struct
// --------------------------------------------------------------------------
type OrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiCommand struct {
	RequestID string                 `json:"request_id" validate:"required,uuid"`
	Timestamp time.Time              `json:"timestamp" validate:"required"`
	Payload   map[string]interface{} `json:"payload" validate:"required"`
}

// --------------------------------------------------------------------------
// 3. Domain Repository Port
// --------------------------------------------------------------------------
type IOrquestacionDeSagaIdempotenteConGoroutinesEnGo122YChiRepository interface {
	FindByID(ctx context.Context, id string) (interface{}, error)
	Save(ctx context.Context, entity interface{}) error
	Delete(ctx context.Context, id string) error
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
type IEventPublisher interface {
	Publish(ctx context.Context, event IDomainEvent) error
}
